### ISSUE TITLE
图片pdf不行,word也不行，加图片pdf图片表格分析处理工具吧，docx也索引不了

### ISSUE THREAD

**Issue by tqangxl** [yuntianhe2014/Easy-RAG#5]
开始创建数据库 ....

上传的文件不能删除，相同文件多次上传，加个hash检测？
Traceback (most recent call last):
  File "D:\Program Files\Python311\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\Lib\Dev\AI\Easy-RAG\Easy-RAG\webui.py", line 317, in handle_vectorize
    vectorize_result, status = asyncio.run(async_vectorize_files(selected_files, selected_knowledge_base, new_kb_name, chunk_size, chunk_overlap))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Lib\Dev\AI\Easy-RAG\Easy-RAG\webui.py", line 75, in async_vectorize_files
    vectordb.create_collection(selected_files, knowledge_base, chunk_size=chunk_size, chunk_overlap=chunk_overlap)
  File "D:\Lib\Dev\AI\Easy-RAG\Easy-RAG\embeding\faissdb.py", line 55, in create_collection
    data = self.parse_data(file)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Lib\Dev\AI\Easy-RAG\Easy-RAG\embeding\faissdb.py", line 30, in parse_data
    data = loaders.load()
           ^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\langchain_core\document_loaders\base.py", line 29, in load
    return list(self.lazy_load())
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\langchain_community\document_loaders\unstructured.py", line 88, in lazy_load
    elements = self._get_elements()
               ^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\site-packages\langchain_community\document_loaders\pdf.py", line 71, in _get_elements
    from unstructured.partition.pdf import partition_pdf
  File "D:\Program Files\Python311\Lib\site-packages\unstructured\partition\pdf.py", line 17, in <module>
    from pdfminer.utils import open_filename
ImportError: cannot import name 'open_filename' from 'pdfminer.utils' (D:\Program Files\Python311\Lib\site-packages\pdfminer\utils.py)

![image](https://github.com/user-attachments/assets/b3455d94-d727-4a3b-9a1b-5a6da242a7e1)

**Comment by yuntianhe2014** [comment]
目前还不支持图片，我找时间优化一下
